import datetime

unique_book_titles = int(input(f"Enter the number of unique book titles: "))

book_title = 0

book_list = []

for n in range(unique_book_titles):
    book_title = book_title + 1
    user_book_title = input(f"\nBook title #{book_title}: ")
    book_sticker_price = float(input(f"Book ({user_book_title}) sticker price: "))
    book_quantity = int(input(f"Book ({user_book_title}) quantity: "))
    book_publication_year = int(input(f"Book ({user_book_title}) publication year: "))
    book_isbn = input(f"Book ({user_book_title}) ISBN: ")
    price = book_sticker_price * book_quantity
    if 1990 <= book_publication_year <= 2000:
        price = .75 * price
    if book_publication_year == 2021:
        price = 1.05 * price
    if book_isbn == book_isbn[::-1]:
        price = price - 10 * book_quantity
    if book_publication_year <= 1986:
        price = 0
    if price < 0:
        price = 0
    book_list.append([user_book_title, book_sticker_price, book_quantity, book_publication_year, book_isbn, price])

print(f"\n110 Library Receipt")

today_date = datetime.date.today().strftime("%B %d, %Y")
today_time = (datetime.datetime.now() + datetime.timedelta(hours=0)).strftime('%H:%M')

print(f"Date: {today_date}")
print(f"Time: {today_time}")
print(f"Number of unique book titles: {unique_book_titles}\n")

print(f"{'Quantity':<10}{'Title':<30}{'ISBN':<20}{'Price':<10}")

for books in book_list:
    print(f"{books[2]:<10}{books[0]:<30}{books[4]:<20}${float(round(books[5], 2)):<10}")

subtotal = 0
tax = 0
total = 0

for books in book_list:
    subtotal = subtotal + books[5]
    tax = tax + books[5] * .0825
    total = subtotal + tax

print(f"\n{'Subtotal':<10}{'':<30}{'':<20}${float(round(subtotal, 2)):<10}")
print(f"{'Tax':<10}{'':<30}{'':<20}${round(tax, 2):<10}")
print(f"{'Total':<10}{'':<30}{'':<20}${round(total, 2):<10}")

print(f"Generated by Library Management App")
